=== Vijeyakumar26/training/Adv Java/XMLDemo/customers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.htc.com/customers"
	xmlns="http://www.htc.com/customers"
	elementFormDefault="qualified">

	<xsd:element name="customers" type="customers_ty" />
	<xsd:complexType name="customers_ty">
		<xsd:sequence>
			<xsd:element name="customer" type="customer_ty"
				minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="customer_ty">
		<xsd:sequence>
			<xsd:element name="account-no" type="xsd:string" />
			<xsd:element name="customer-name" type="xsd:string" />
			<xsd:element name="account-type" type="xsd:string" />
			<xsd:element name="bank-name" type="xsd:string" />
			<xsd:element name="branch" type="xsd:string" />
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string" />
	</xsd:complexType>
</xsd:schema>

=== Vijeyakumar26/training/Adv Java/XMLDemo/customers.xml
<?xml version="1.0" encoding="UTF-8"?>
<customers xmlns="http://www.htc.com/customers"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.htc.com/customers customers.xsd">

		<customer id="C001">
			<account-no>603318654154</account-no>
			<customer-name>bala</customer-name>
			<account-type>savings</account-type>
			<bank-name>axis</bank-name>
			<branch>chennai</branch>
		</customer>
		
		<customer id="C0012">
			<account-no>603318654153</account-no>
			<customer-name>Pugazh</customer-name>
			<account-type>savings</account-type>
			<bank-name>HDFC</bank-name>
			<branch>chennai</branch>
		</customer>

</customers>
