=== Vijeyakumar26/training/Adv Java/XMLDemo/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.htc.com/employee"
	xmlns="http://www.htc.com/employee"
	elementFormDefault="qualified">

	<xsd:element name="employees" type="employees_ty" />
	<xsd:complexType name="employees_ty">
		<xsd:sequence>
			<xsd:element name="employee" type="employee_ty"
				minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="employee_ty">
		<xsd:sequence>
			<xsd:element name="firstname" type="xsd:string" />
			<xsd:element name="title" type="xsd:string" />
			<xsd:element name="building" type="xsd:string" />
			<xsd:element name="room" type="xsd:integer" />
			<xsd:element name="supervisor" type="xsd:string" />
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string" />
	</xsd:complexType>
</xsd:schema>

=== Vijeyakumar26/training/Adv Java/XMLDemo/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<employees xmlns="http://www.htc.com/employee" 
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		  xsi:schemaLocation="http://www.htc.com/employee employee.xsd">
		  
	<employee id="be129">
        <firstname>Jane</firstname>
        <title>Engineer</title>
        <building>327</building>
        <room>19</room>
        <supervisor>be131</supervisor>
    </employee>
    
    <employee id="be130">
        <firstname>Don</firstname>
        <title>Doctor</title>
        <building>324</building>
        <room>13</room>
        <supervisor>be323</supervisor>
    </employee>
    
    <employee id="be131">
        <firstname>Dan</firstname>
        <title>Teacher</title>
        <building>323</building>
        <room>12</room>
        <supervisor>be234</supervisor>
    </employee>

</employees>
