=== Vijeyakumar26/training/Adv Java/XMLDemo/hospital.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://www.htc.com/hospital" 
		xmlns="http://www.htc.com/hospital" 
		elementFormDefault="qualified">

	<xsd:element name="hospital" type="hospital_ty" />
	<xsd:complexType name="hospital_ty">
		<xsd:sequence>
			<xsd:element name="doctor" type="doctor_ty" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="doctor_ty">
		<xsd:sequence>
			<xsd:element name="doctorid" type="xsd:string" />
			<xsd:element name="doctorname" type="xsd:string" />
			<xsd:element name="speciality" type="xsd:string" />
			<xsd:element name="experience" type="xsd:integer" />
		</xsd:sequence>
		<xsd:attribute name="regno" type="xsd:string" />
	</xsd:complexType>

</xsd:schema>

=== Vijeyakumar26/training/Adv Java/XMLDemo/hospital.xml
<?xml version="1.0" encoding="UTF-8"?>
<hospital xmlns="http://www.htc.com/hospital" 
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		  xsi:schemaLocation="http://www.htc.com/hospital hospital.xsd">
		  
<doctor regno="434343">
		<doctorid>d01232</doctorid>
		<doctorname>Rahul</doctorname>
		<speciality>Heart</speciality>
		<experience>10</experience>
	</doctor>
	<doctor regno="434345">
		<doctorid>d01235</doctorid>
		<doctorname>Kishore</doctorname>
		<speciality>Urology</speciality>
		<experience>19</experience>
	</doctor>
	<doctor regno="434344">
		<doctorid>d01233</doctorid>
		<doctorname>Gokul</doctorname>
		<speciality>Heart</speciality>
		<experience>12</experience>
	</doctor>
	<doctor regno="434348">
		<doctorid>d01239</doctorid>
		<doctorname>Dhananjeyan</doctorname>
		<speciality>Heart</speciality>
		<experience>13</experience>
	</doctor>
</hospital>
