=== Vijeyakumar26/training/Adv Java/XMLDemo/service.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.htc.com/service"
	xmlns="http://www.htc.com/service"
	elementFormDefault="qualified">
	
	<xsd:element name="service" type="service_ty" />
	<xsd:complexType name="service_ty">
		<xsd:sequence>
			<xsd:element name="automobile" type="automobile_ty"
				minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="automobile_ty">
		<xsd:sequence>
			<xsd:element name="type" type="xsd:string" />
			<xsd:element name="name" type="xsd:string" />
			<xsd:element name="company" type="xsd:string" />
			<xsd:element name="kilometer" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== Vijeyakumar26/training/Adv Java/XMLDemo/service.xml
<?xml version="1.0" encoding="UTF-8"?>
<service xmlns="http://www.htc.com/service"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.htc.com/service service.xsd">

	<automobile>
		<type>four-wheeler</type>
		<name>Ertiga</name>
		<company>Maruti</company>
		<kilometer>548720</kilometer>
	</automobile>
	
	<automobile>
		<type>four-wheeler</type>
		<name>Xylo</name>
		<company>Mahindra</company>
		<kilometer>54800</kilometer>
	</automobile>

</service>
